// Canonical city data for /areas-we-serve/* pages.
// Each slug must match the actual Next.js route segment exactly.
export const AREAS = [
  {
    slug: 'burbank',
    name: 'Burbank',
    county: 'Los Angeles County',
    region: 'San Fernando Valley',
    tagline: 'SEO & Digital Marketing in Burbank, CA',
    desc: 'Burbank is home to major entertainment studios, production companies, and thousands of small businesses. Gobiya helps Burbank businesses get found on Google, AI search, and beyond.',
    details: [
      'Steps from Warner Bros., Disney, and NBC Universal — Burbank businesses compete in one of the most media-savvy markets in the country.',
      'We help local shops, restaurants, medical offices, and service companies in Burbank rank #1 on Google Maps and organic search.',
      'Our AI & GEO search strategy ensures your Burbank business gets cited by ChatGPT, Perplexity, and Google AI Overviews.',
    ],
  },
  {
    slug: 'echo-park',
    name: 'Echo Park',
    county: 'Los Angeles County',
    region: 'East Los Angeles',
    tagline: 'SEO & Digital Marketing in Echo Park, LA',
    desc: 'Echo Park is a vibrant, artistic neighborhood with a growing small business scene. Gobiya helps Echo Park businesses build a strong online presence and capture local search traffic.',
    details: [
      'Echo Park\'s diverse mix of boutiques, cafés, fitness studios, and creative agencies all benefit from strong local SEO.',
      'We specialize in Google Business Profile optimization and local map pack rankings for Echo Park neighborhoods.',
      'Our content strategies help Echo Park businesses get cited by AI tools and dominate niche local search queries.',
    ],
  },
  {
    slug: 'hollywood',
    name: 'Hollywood',
    county: 'Los Angeles County',
    region: 'Central Los Angeles',
    tagline: 'SEO & Digital Marketing in Hollywood, CA',
    desc: 'Hollywood is one of the most searched locations in the world. Gobiya helps Hollywood businesses stand out on Google, rank above competitors, and get found by AI assistants.',
    details: [
      'From the Walk of Fame to Highland Ave, Hollywood businesses face enormous online competition — we help you win it.',
      'We build AI-ready content architectures that get Hollywood restaurants, hotels, studios, and agencies cited by ChatGPT and Claude.',
      'Our PPC management drives high-intent foot traffic and online leads for Hollywood businesses of every size.',
    ],
  },
  {
    slug: 'los-feliz',
    name: 'Los Feliz',
    county: 'Los Angeles County',
    region: 'East Hollywood / Eastside',
    tagline: 'SEO & Digital Marketing in Los Feliz, LA',
    desc: 'Los Feliz is a tree-lined, community-centered neighborhood with a loyal local customer base. Gobiya helps Los Feliz businesses grow their search presence and attract more local customers.',
    details: [
      'Los Feliz\'s boutique shops, health clinics, yoga studios, and restaurants all compete for local search visibility.',
      'We help Los Feliz businesses rank on Google Maps and appear in AI search results for local intent queries.',
      'Our white-hat, honest approach has helped Los Angeles Eastside businesses grow online since 2010.',
    ],
  },
  {
    slug: 'sherman-oaks',
    name: 'Sherman Oaks',
    county: 'Los Angeles County',
    region: 'San Fernando Valley',
    tagline: 'SEO & Digital Marketing in Sherman Oaks, CA',
    desc: 'Sherman Oaks is a major commercial and residential hub in the San Fernando Valley. Gobiya has helped Sherman Oaks businesses recover from ranking drops and grow their digital presence since 2010.',
    details: [
      'Sherman Oaks is one of the Valley\'s most competitive local search markets — especially for legal, dental, and medical practices.',
      'We provide technical SEO audits, Google Business Profile recovery, and PPC management for Sherman Oaks businesses.',
      'Our team is local to the San Fernando Valley and understands the Sherman Oaks market inside and out.',
    ],
  },
  {
    slug: 'silver-lake',
    name: 'Silver Lake',
    county: 'Los Angeles County',
    region: 'East Los Angeles',
    tagline: 'SEO & Digital Marketing in Silver Lake, LA',
    desc: 'Silver Lake is one of LA\'s most trendy and digitally-savvy neighborhoods. Gobiya helps Silver Lake businesses build strong SEO foundations and compete in a fast-moving local market.',
    details: [
      'Silver Lake\'s creative economy — from coffee shops to design studios — depends on strong online visibility to attract customers.',
      'We specialize in content strategy and AI-ready SEO that helps Silver Lake businesses get recommended by AI tools.',
      'Our transparent, no-contract approach has made us a trusted partner for Silver Lake small businesses since 2010.',
    ],
  },
  {
    slug: 'studio-city',
    name: 'Studio City',
    county: 'Los Angeles County',
    region: 'San Fernando Valley',
    tagline: 'SEO & Digital Marketing in Studio City, CA',
    desc: 'Studio City is a prime upscale neighborhood at the foot of the Hollywood Hills. Gobiya helps Studio City businesses achieve top Google rankings and AI search visibility.',
    details: [
      'Studio City\'s restaurants, boutiques, and professional services all compete for top local search placement.',
      'We help Studio City businesses rank on Google Maps, recover from algorithm updates, and grow with paid ads.',
      'Our team has served Studio City and the surrounding Valley area for over 16 years.',
    ],
  },
  {
    slug: 'koreatown',
    name: 'Koreatown',
    county: 'Los Angeles County',
    region: 'Central Los Angeles',
    tagline: 'SEO & Digital Marketing in Koreatown, LA',
    desc: 'Koreatown is one of LA\'s densest and most vibrant urban neighborhoods, with thousands of businesses competing for visibility. Gobiya helps Koreatown businesses win on Google, Yelp, and AI search.',
    details: [
      'Koreatown\'s restaurants, spas, medical offices, and retail shops face one of LA\'s most competitive local search environments.',
      'We provide bilingual-aware content strategies and AI search optimization for Koreatown businesses serving diverse communities.',
      'Our Google Business Profile and local SEO services have helped Koreatown businesses recover and grow their digital footprint.',
    ],
  },
  {
    slug: 'downtown',
    name: 'Downtown Los Angeles',
    county: 'Los Angeles County',
    region: 'Central Los Angeles',
    tagline: 'SEO & Digital Marketing in Downtown LA',
    desc: 'Downtown Los Angeles is the business and cultural heart of the city. Gobiya helps DTLA businesses rank higher, attract more customers, and dominate both Google and AI search results.',
    details: [
      'Downtown LA is home to law firms, financial services, hotels, restaurants, and thousands of small businesses all competing online.',
      'We provide comprehensive SEO, PPC management, and AI search strategies for businesses in the DTLA market.',
      'Our team helps Downtown LA businesses get cited in AI assistants, recover from Google ranking drops, and build lasting search authority.',
    ],
  },
];
