// Flat, keyword-first service pages — Los Angeles targeted format,
// each backed by a real testimonial and a real, already-verified datapoint
// (never fabricated — same bar as lib/searchWins.js and lib/clientSearchWins.js).

export const SERVICES_FLAT = {
  'seo-services-los-angeles': {
    slug: 'seo-services-los-angeles',
    title: 'Los Angeles SEO Services | Technical & Local SEO',
    eyebrow: 'Los Angeles SEO Services · Get Found on Google',
    h1: 'Los Angeles SEO Services to Help Your Business Get Found',
    heroCtaText: 'Request a Free SEO Check',
    heroCtaHref: '/free-site-scan?goal=rankings',
    metaDescription: 'Los Angeles SEO services that fix what is blocking Google, then build rankings and AI visibility. Founder-led, no long-term contracts. Free site scan.',
    // Named as plain text, never links: all 18 of these URLs now 308 to this
    // page, so linking them would re-fragment what the redirects consolidated.
    serviceAreas: [
      'Glendale', 'Studio City', 'Beverly Hills', 'Encino', 'Woodland Hills',
      'Northridge', 'Sherman Oaks', 'Santa Monica', 'Long Beach', 'Anaheim',
      'Burbank', 'Costa Mesa', 'Culver City', 'North Hollywood', 'Silverlake',
      'Van Nuys', 'Ventura', 'Santa Clarita',
    ],
    intro: 'SEO for Los Angeles businesses starts with one simple question: can Google actually read your page? If it can’t, no amount of content or links will save you. We fix that basic technical problem first — making sure your site loads fast and search engines can find and understand it — before building content and trust on top of that foundation. It’s the same approach that took SafetyCentric’s organic search impressions up 113% in 90 days, verified directly in Google Search Console. Request a free SEO check to see what’s actually capping your traffic.',
    testimonial: {
      quote: 'Moving off WordPress was the part I was most nervous about and it turned out to be the easy part. The bigger deal was the CRM and the drip campaigns — leads used to sit in an inbox until someone remembered them. Now they get followed up whether I’m paying attention or not.',
      name: 'Pete Urueta',
      company: 'Safety-Centric.com',
      role: 'Business Security Systems Services',
      photo: '/assets/img/pete-urueta-ceo.webp',
      href: '/work/safetycentric',
    },
    datapoint: {
      value: 113,
      decimals: 0,
      suffix: '%',
      label: 'Increase in organic search impressions for one client in 90 days',
      sourceNote: 'Verified in Google Search Console — see the live number on the SafetyCentric case study.',
      href: '/work/safetycentric',
    },
    problem: {
      eyebrow: 'The problem',
      statement: 'A site can look finished and still be invisible to Google — blocked pages, a blank screen where content should load, and missing technical details quietly capping your traffic no matter how much content you publish on top of it.',
    },
    capabilities: [
      { tag: 'Rendering', title: 'Server-side rendering', href: '/glossary/server-side-rendering', desc: 'Google cannot rank a page it cannot read. If your site hands the crawler an empty shell and loads the real content a second later, that is the whole problem — and we fix it at the source.' },
      { tag: 'Recovery', title: 'Algorithm & penalty recovery', href: '/insights/why-did-my-website-traffic-drop', desc: 'An algorithm update and a manual penalty look identical from the outside, and the recovery for each is completely different. Getting that diagnosis right is most of the job.' },
      { tag: 'Schema', title: 'Structured data', href: '/glossary/schema-markup', desc: 'AI tools do not guess what your business is. They read the details underneath the page, so we write yours properly — services, locations, FAQs, all of it.' },
      { tag: 'Speed', title: 'Core Web Vitals', href: '/glossary/core-web-vitals', desc: 'Fast in your browser and fast to Google are two different measurements. We tune yours to the one Google actually scores, without adding another plugin to the pile.' },
      { tag: 'Keywords', title: 'Keyword research & strategy', href: '/glossary/keyword-research', desc: 'The phrase with 12,000 searches a month rarely pays your bills. The one somebody types right before they call usually does. That is the list we build.' },
      { tag: 'Authority', title: 'Link building & digital PR', href: '/glossary/backlink', desc: 'Links get earned here, not bought — real coverage on sites people actually read. Bulk link packages are the cheap fix that turns expensive about a year later.' },
      { tag: 'On-page', title: 'On-page SEO', href: '/glossary/internal-linking', desc: 'Most sites quietly compete against themselves, two or three pages chasing the same phrase. Sorting out titles, headings and internal links is often the cheapest win on the table.' },
      { tag: 'Local', title: 'Local SEO & Google Business Profile', href: '/glossary/google-business-profile', desc: 'The map results run on trust: a claimed profile, details that match everywhere Google checks, and a business that looks like it is really there. We clean yours up and keep it that way.' },
      { tag: 'Content', title: 'Content strategy', href: '/glossary/local-seo', desc: 'Write for the question and both Google and ChatGPT can lift the answer straight off your page. That is the entire trick, and almost nobody bothers.' },
    ],
    process: [
      { step: '01', title: 'Technical audit', desc: 'First the truth — exactly what Googlebot and the AI crawlers get when they hit your site, which is rarely what your browser shows you.' },
      { step: '02', title: 'Fix the foundation', desc: 'Nothing else gets touched until Google can find and read your pages. Content published on a broken foundation is money spent twice.' },
      { step: '03', title: 'Structured data & layout', desc: 'Then the structured details go in and the site gets reorganised around how people in your industry search, rather than how your company is organised internally.' },
      { step: '04', title: 'Verify & monitor', desc: 'Every fix gets confirmed in Search Console rather than assumed, and you get a plain record of what changed, when, and what moved afterward.' },
    ],
    faqs: [
      { q: 'How much should I expect to pay for SEO?', a: 'For professional, white-hat SEO from an experienced agency or strategist, most small to medium businesses in Los Angeles pay between $1,500 and $5,000 per month for ongoing retainers, or $3,500 to $10,000+ for single comprehensive technical site audits and initial rebuilds. Cheaper services under $500/month often rely on automated spam, fake link networks, or low-quality AI content that carries a high risk of Google penalties. Check out our clear <a href="/pricing">pricing packages</a> to see exact tier breakdowns.' },
      { q: 'Is SEO dead or evolving in 2026?', a: 'SEO is far from dead — but traditional keyword-stuffing and cheap link building are extinct. In 2026, search engine optimization has evolved into <strong>Generative Engine Optimization (GEO)</strong> and technical content authority. Search engines and AI recommendation systems like Google AI Overviews, ChatGPT, Claude, and Perplexity synthesize answers directly from trusted, verified brand sources. The businesses that rank today are those that optimize for human search intent, schema markup, and authoritative brand citations.' },
      { q: 'How much does it cost to hire an SEO company?', a: 'The cost to hire a reputable SEO company typically ranges from $2,000 to $7,500 per month depending on your market competitiveness, industry scope, and technical complexity. Hourly consulting rates range between $150 and $350 per hour. At Gobiya, we offer flexible month-to-month plans without long-term lock-in contracts so you get clear, accountable performance every month. Learn more on our <a href="/pricing">transparent pricing page</a>.' },
      { q: 'What does an SEO company do?', a: 'A professional SEO company analyzes, optimizes, and scales your website’s visibility across search engines and AI discovery platforms. Core responsibilities include: 1) <strong>Technical SEO</strong> (fixing indexation errors, page load speeds, and server-side rendering), 2) <strong>Content Architecture & Keyword Strategy</strong> (building authoritative content aligned with high-intent buyers), 3) <strong>Digital PR & Authority Building</strong> (earning genuine media citations and clean local listings), and 4) <strong>Conversion Rate Optimization</strong> (ensuring incoming search traffic turns into booked leads).' },
      { q: 'What is the 80/20 rule for SEO?', a: 'The 80/20 rule (Pareto Principle) for SEO states that 80% of your search traffic, leads, and revenue come from 20% of your technical fixes, high-intent keywords, and core landing pages. Rather than wasting budget publishing hundreds of low-quality articles, we focus on the vital 20% — fixing critical technical code errors blocking Google, targeting bottom-of-funnel commercial searches, and building high-trust authority signals that drive real customer calls.' },
      { q: 'How do we know if our traffic drop is an algorithm update or something we did?', a: 'We compare the date of your drop against known Google updates, look at which pages and search terms lost traffic, and check Search Console for any direct penalty notices. A Google update usually hits a broad group of pages at once; a direct penalty comes with a clear notice and follows a specific rule violation.' },
      { q: 'Our developer says the site is fast. Why isn’t it ranking?', a: 'Loading fast in a browser and being readable to Google are two different things. A site can score well on a speed test and still show search engines a blank page if all the content loads after the page opens. We test your site the same way search engines and AI tools actually see it, not just with a speed score.' },
      { q: 'Do we need to rebuild our whole site to fix this?', a: 'Usually not. Most technical SEO problems can be fixed without starting over — the underlying issues can typically be layered onto your existing website. A <a href="/web-development-services-los-angeles">full rebuild</a> is only the right call when your current platform genuinely can’t be fixed.' },
      { q: 'What is an organic search strategy?', a: 'An organic search strategy is your plan for earning free search traffic instead of paying for every click — it covers the technical setup, the right keywords, how your content is organized, and building real trust so your pages match what people are actually searching for. Unlike paid ads, good rankings keep paying off over time, long after the initial work is done. We start with the technical basics, then build content and trust on top. See real examples in our <a href="/work">client case studies</a>.' },
      { q: 'How have search engine algorithms evolved?', a: 'Search engines have moved from simply matching keywords to actually understanding what a page means and how trustworthy it is. Early updates like Panda and Penguin punished thin content and fake links. Later updates helped Google understand the meaning behind a search, not just the exact words typed in. More recent updates reward real expertise and genuinely useful content. AI Overviews add a new layer on top: content now competes to be quoted by AI, not just ranked in a list. We’ve tracked and adjusted to every major update since 2010. See our guide on <a href="/insights/why-did-my-website-traffic-drop">figuring out why your traffic dropped</a>.' },
      { q: 'What is on-page SEO, and do I need it?', a: 'On-page SEO is the work done on the page itself: the title, the headings, how the text is written, and how pages link to each other. It is usually the cheapest place to find wins, because you control all of it. Most sites we look at have pages competing against each other for the same phrase without anyone noticing.' },
      { q: 'Do you work with service businesses like contractors, clinics, and law firms?', a: 'Yes, and that is most of our work. Service businesses live or die on the phone ringing, so we care more about calls booked than about a ranking screenshot. Our <a href="/work">case studies</a> include a dental group, a security integrator, a plumbing company, and a fingerprinting service, all in Southern California.' },
      { q: 'Do you cover my area outside central Los Angeles?', a: 'Yes. We work across Los Angeles County and into Orange and Ventura counties, including Glendale, Burbank, Studio City, Sherman Oaks, Encino, Woodland Hills, Northridge, Van Nuys, North Hollywood, Culver City, Santa Monica, Beverly Hills, Long Beach, Anaheim, Costa Mesa, Santa Clarita and Ventura. The work is the same wherever you are.' },
    ],
    ctaTitle: 'Find out what’s actually capping your traffic.',
  },

  'geo-services-los-angeles': {
    slug: 'geo-services-los-angeles',
    title: 'Los Angeles GEO Services | AI Search Visibility',
    eyebrow: 'Los Angeles GEO Services · AI Search Optimization',
    h1: 'Los Angeles GEO Services Built for ChatGPT & AI Search',
    metaDescription: 'Los Angeles GEO services built to get your local business mentioned by ChatGPT, Perplexity, and Google’s AI answers. Free content check.',
    intro: 'AI tools like ChatGPT don’t reward typical marketing copy — they pull clear, direct answers from pages they already trust. We write your content around the exact questions Los Angeles customers ask ChatGPT and Perplexity, so your LA business gets quoted first. We back this up with real research: our AI Citation Study asked five different AI assistants the same 200 questions and tracked exactly who they recommended, and why. One client, The Healing Metta, now shows up when people ask ChatGPT about integrative care in their area — that wasn’t true a year ago. Request a free content check to see where you’re missing out on AI recommendations.',
    testimonial: {
      quote: 'Users were finding answers about our treatments everywhere except from us. The shift was writing for the questions people actually ask, and structuring it so the AI tools could read it properly. When someone asks ChatGPT about integrative care in our area now, we come up. That wasn’t true a year ago.',
      name: null,
      company: 'The Healing Metta',
      role: 'Secrets of Buddha',
      photo: null,
      href: '/work/the-healing-metta',
    },
    datapoint: {
      value: 34,
      decimals: 0,
      suffix: '%',
      label: 'Growth in blended organic search visibility across every account we run this quarter',
      sourceNote: 'The same underlying visibility AI answer engines pull from — see our AI Citation Study for how we track actual AI citations directly.',
      href: '/insights/ai-citation-study',
    },
    problem: {
      eyebrow: 'The problem',
      statement: 'Most website writing is meant to persuade a person scrolling down a page — not to be read and quoted by an AI tool looking for a clear, direct answer to a specific question.',
    },
    capabilities: [
      { tag: 'Structure', title: 'Answer-first writing', href: '/glossary/answer-engine-optimization', desc: 'AI tools scan for the answer, not the wind-up. Put it in the first two sentences, back it with real substance, and you become the source instead of the runner-up.' },
      { tag: 'Research', title: 'Prompt-mapped content', href: '/glossary/generative-engine-optimization', desc: 'People type whole questions into ChatGPT, not keywords. We build your content from those real questions — the ones a keyword tool will never show you.' },
      { tag: 'Format', title: 'FAQ & comparison pages', href: '/glossary/featured-snippet', desc: 'Clear questions, direct answers, honest side-by-side comparisons. These are the formats AI assistants quote most, and they happen to be what buyers wanted anyway.' },
      { tag: 'Voice', title: 'SEO-mapped web copy', href: '/content-marketing-services-los-angeles', desc: 'Your service pages have two jobs: get found, then convince. We write them to do both, instead of circling a keyword and hoping.' },
    ],
    process: [
      { step: '01', title: 'Question research', desc: 'It starts with what people genuinely ask about a business like yours, pulled from real prompts and searches rather than assumptions.' },
      { step: '02', title: 'Content planning', desc: 'Then the page gets a shape — the answer up top where it gets quoted, the depth underneath where it earns the trust.' },
      { step: '03', title: 'Write & structure', desc: 'The writing has to work twice over: clear enough for a person deciding, structured enough for a model extracting.' },
      { step: '04', title: 'Track citations', desc: 'Indexed is not the same as cited. We run your target questions through ChatGPT, Perplexity and Google AI answers to see whether your name actually comes up.' },
    ],
    faqs: [
      { q: 'Is this just SEO copywriting with a new name?', a: 'It shares the same foundation as our <a href="/content-marketing-services-los-angeles">content marketing</a> work — clear, well-organized, genuinely useful writing. This adds one more layer, specific to how AI tools pull information: a direct answer near the top, clear structure, and wording that’s easy to quote without losing its meaning.' },
      { q: 'Can you rewrite our existing content instead of starting from scratch?', a: 'In most cases, yes. A lot of underperforming pages already have the right information — they just need to be reorganized around a direct answer and cleaner formatting. We check your existing pages first and only recommend starting over when the content itself is too thin to fix.' },
      { q: 'How do you measure whether this is working?', a: 'We track two things: your regular Google rankings and traffic, and whether AI tools are actually mentioning you — <a href="/insights/get-cited-by-chatgpt-perplexity-ai-overviews">running your target questions through ChatGPT, Perplexity, and Google’s AI answers</a> regularly to see if your pages get quoted.' },
      { q: 'What AI marketing tools does Gobiya use for content optimization?', a: 'We use AI tools for research — finding the actual questions people ask ChatGPT and Perplexity — plus organizing content and tracking whether client pages get mentioned. The actual writing and editorial decisions stay with our team: AI tools speed up research, they don’t replace human judgment. For a broader look at choosing and using AI tools across your business, see our <a href="/ai-consulting-services-los-angeles">AI consulting</a> work.' },
      { q: 'How does AI change search engine results pages?', a: 'AI has added a new layer at the top of the page — Google’s AI Overviews, and the answer screens in ChatGPT and Perplexity — that summarizes and quotes sources before someone even clicks a link. Your content now competes two ways: the usual ranking for a spot in the list, and separately, getting picked to be part of that AI summary. Those two things follow different rules, which is why <a href="/geo-services-los-angeles">getting found by AI tools</a> is now its own skill alongside traditional SEO. Read more in our guide on <a href="/insights/zero-click-search-ai-overviews-small-business">what it means when people stop clicking links at all</a>.' },
    ],
    ctaTitle: 'Write content an AI actually wants to quote.',
  },

  'ppc-management-services-los-angeles': {
    slug: 'ppc-management-services-los-angeles',
    title: 'Los Angeles PPC Management | Google Ads Agency',
    eyebrow: 'Los Angeles PPC Management Services · Cost Per Lead',
    h1: 'Los Angeles PPC Management Services That Bring Real Leads',
    heroCtaText: 'Request a Free Ads Check',
    heroCtaHref: '/free-site-scan?goal=sales',
    metaDescription: 'Los Angeles PPC management services built around real leads, not just clicks — custom Google Ads campaigns and matching landing pages for LA businesses.',
    intro: 'Most Google Ads management focuses on getting clicks, not booked customers. We rebuild your ad campaigns for the Los Angeles market, block out bad searches, and match your landing pages around the cost of a real customer. Every account gets a full review before we change a dollar of spend. One client, Trusted Home Contractors, cut their cost per real customer by roughly 40% once we rebuilt campaigns around what people were actually searching for and sent them to pages that matched. Request a free Google Ads check to see where your budget is leaking.',
    testimonial: {
      quote: 'Our ads were working in the sense that the phone rang. They weren’t working in the sense that most of those calls were tire-kickers. Rebuilding the campaigns around what people were actually searching for, and sending them to pages that matched, cut what we pay per real customer by about 40%.',
      name: 'Mike P.',
      company: 'Trusted Home Contractors',
      role: 'General Contractor',
      photo: '/assets/img/testimonial-mike.png',
      href: '/work',
    },
    datapoint: {
      value: 40,
      decimals: 0,
      suffix: '%',
      label: 'Reduction in cost per real customer for one client',
      sourceNote: 'Client-reported result — PPC spend isn’t tracked in Google Search Console, so this is the account’s own reporting, not GSC-verified.',
      href: '/work',
    },
    problem: {
      eyebrow: 'The problem',
      statement: 'Loosely-matched keywords, a short block-list, and a landing page that doesn’t match what people searched for quietly burn your budget on clicks that were never going to become customers.',
    },
    capabilities: [
      { tag: 'Structure', title: 'Campaign rebuilds', href: '/glossary/google-ads', desc: 'Loose keywords bleed budget quietly, every day, forever. Tight ad groups and a block-list we update weekly stop it at the source.' },
      { tag: 'Conversion', title: 'Landing page alignment', href: '/glossary/ppc-landing-page', desc: 'The fastest way to waste a good click is to send it somewhere that does not match the ad. Every page gets built to keep the promise the ad made.' },
      { tag: 'Tracking', title: 'Conversion & call tracking', href: '/glossary/conversion-tracking', desc: 'Form fills are a proxy. Booked jobs and answered calls are the number that matters, so that is what the tracking runs all the way through to.' },
      { tag: 'Testing', title: 'Bid & creative testing', href: '/glossary/smart-bidding', desc: 'Testing against click-through tells you which ad is catchy. Testing against cost per booked lead tells you which one is profitable. Only one of those pays you.' },
      { tag: 'Production', title: 'AI-generated video assets', href: '/ai-consulting-services-los-angeles', desc: 'Campaign video in days rather than a production schedule. AI tools handle the shoot, so testing new creative stops being a budget conversation.' },
      { tag: 'Variants', title: 'Creative variant testing', href: '/glossary/return-on-ad-spend', desc: 'One hook is a guess. Six hooks, measured against each other, is an answer — and producing six is now cheap enough to be worth doing.' },
    ],
    process: [
      { step: '01', title: 'Account review', desc: 'Before a dollar of spend moves, we read the account line by line to find exactly where budget leaks on searches that were never going to buy.' },
      { step: '02', title: 'Rebuild structure', desc: 'Campaigns get rebuilt around real buyer intent, and the money-burning searches get blocked straight away. Usually the fastest saving in the whole account.' },
      { step: '03', title: 'Align landing pages', desc: 'Then every ad gets a page that matches it. This single change closes more of the gap between click and sale than bid tweaking ever has.' },
      { step: '04', title: 'Optimize to cost per lead', desc: 'After that it is steady work on bids, budget and creative — all judged against the cost of a booked lead, and reported to you every month.' },
    ],
    faqs: [
      { q: 'Our click-through rate is good — why is cost per lead still high?', a: 'How many people click your ad only shows whether the ad is eye-catching — it doesn’t show whether that traffic actually turns into customers. A lot of clicks but a high cost per lead usually means loosely-matched keywords are pulling in the wrong people, or your landing page doesn’t follow through on what the ad promised.' },
      { q: 'How much should we be spending on Google Ads?', a: 'It depends on how much profit you make per customer and what a lead currently costs you — not a general rule of thumb. We usually start by rebuilding your campaigns within your existing budget to prove real improvement before recommending you spend more.' },
      { q: 'Do you handle both the ads and the landing pages?', a: 'Yes — matching the ad and the landing page is usually where the biggest gains come from, and it overlaps directly with our <a href="/cro-ux-services-los-angeles">website testing</a> work. A well-run campaign sending traffic to a generic homepage still underperforms. Matching the landing page to what each ad actually promised is often the single biggest fix we make.' },
      { q: 'Does AI-generated video actually perform as well as traditionally produced ads?', a: 'It depends on the format and platform. For short, attention-grabbing social ads, AI-made video performs just as well because viewers care about the message and pacing more than polish. For your main brand video, a traditional shoot may still be the better call.' },
    ],
    ctaTitle: 'Rebuild your ad account around cost per lead, not clicks.',
  },

  'content-marketing-services-los-angeles': {
    slug: 'content-marketing-services-los-angeles',
    title: 'Los Angeles Content Marketing | SEO Copywriting',
    eyebrow: 'Los Angeles Content Marketing Services · Built to Rank',
    h1: 'Los Angeles Content Marketing Services Built to Rank & Convert',
    metaDescription: 'Los Angeles content marketing services that turn articles into real search growth for local businesses. Written for search demand and lead conversions.',
    intro: 'Content marketing usually fails when pages are written to fill a calendar instead of answering what people are searching for. We plan content for Los Angeles businesses around real search demand first, then write it to both rank and convert visitors into customers — not just to hit a word count. One client, RemodelMePros, put it simply: the SEO articles kept homeowners coming in without buying every lead. That same approach took SmileCenter’s organic search impressions up 56% in 90 days, verified in Google Search Console. Request a free content check to see where your current pages are missing real demand.',
    testimonial: {
      quote: 'Two-sided marketplaces are hard and I’d already had one developer tell me it couldn’t be done for what I wanted to spend. The bidding dashboard is what contractors actually log in for, and the SEO articles kept homeowners coming in without me buying every lead. It’s not finished — it probably never is — but it works.',
      name: 'Mike P.',
      company: 'RemodelMePros.com',
      role: 'Contractors Marketplace',
      photo: '/assets/img/testimonial-mike.png',
      href: '/work/remodel-me-pros',
    },
    datapoint: {
      value: 56,
      decimals: 0,
      suffix: '%',
      label: 'Increase in organic search impressions from a content-driven rebuild',
      sourceNote: 'A different client (SmileCenter.com) than the testimonial above, verified in Google Search Console — see the live number on their case study.',
      href: '/work/smile-center-dentistry',
    },
    problem: {
      eyebrow: 'The problem',
      statement: 'Copy stuffed with keywords might rank briefly, but it doesn’t convince anyone to buy. Well-written copy that ignores what people are searching for never gets found in the first place. Most sites end up with one problem or the other.',
    },
    capabilities: [
      { tag: 'Pages', title: 'Core site copy', href: '/content-marketing-services-los-angeles', desc: 'Your homepage, service and about pages carry most of the buying decision. We write them around real searches, with an obvious next step for the reader.' },
      { tag: 'Intent', title: 'Search intent mapping', href: '/glossary/keyword-research', desc: 'Two people typing the same phrase can want completely different things. Every page gets built around what the searcher was actually after.' },
      { tag: 'Voice', title: 'Brand voice development', href: '/content-marketing-services-los-angeles', desc: 'A site written by five people reads like five businesses. Your voice gets defined once, then held everywhere it appears.' },
      { tag: 'Structure', title: 'On-page structure & schema', href: '/glossary/schema-markup', desc: 'Headings and structured details belong in the first draft. Retrofitting them later is slower, more expensive, and never quite fits.' },
      { tag: 'Research', title: 'Topic & gap analysis', href: '/glossary/long-tail-keyword', desc: 'Real demand on one side, competitor coverage on the other. Your content plan lives in the gap between them, and the easy topics are rarely in there.' },
      { tag: 'Architecture', title: 'Content hub planning', href: '/glossary/internal-linking', desc: 'Related articles should feed each other, not split one search between three of your own pages. We plan them as a set for exactly that reason.' },
    ],
    process: [
      { step: '01', title: 'Intent & keyword research', desc: 'Before a word gets written, every planned page is matched to a real search and the real expectation sitting behind it.' },
      { step: '02', title: 'Structure & outline', desc: 'Then the outline — headings that answer the search, and a path through the page that ends somewhere useful for the reader.' },
      { step: '03', title: 'Write & optimize', desc: 'Drafts arrive search-ready, with the technical details already in them rather than handed to somebody else to bolt on later.' },
      { step: '04', title: 'Review & publish', desc: 'You approve it before anything goes live. We publish, then watch how Google and the AI tools respond over the following weeks.' },
    ],
    faqs: [
      { q: 'Will this copy sound like it was written for search engines instead of people?', a: 'That’s exactly what we try to avoid. Good SEO writing today works by genuinely answering what someone’s looking for, in a clear, natural voice — stuffing keywords into a page has actually hurt rankings for years now.' },
      { q: 'Can you write copy for our existing pages, or only new ones?', a: 'Both. A lot of our work is rewriting existing pages that rank poorly or don’t convert, often because they were written for a different question than the one that actually brings in traffic.' },
      { q: 'How do you make sure the copy still sounds like our brand?', a: 'We start by reviewing your existing materials and how your team actually talks to customers, before writing anything. That way the copy sounds like an extension of your business, not a generic template.' },
      { q: 'How much content do we actually need to publish?', a: 'Less than most agencies suggest. A smaller number of well-researched, well-organized pieces aimed at real demand consistently beats a big calendar of thin, low-value posts.' },
      { q: 'How do you decide what topics are worth covering?', a: 'We weigh how many people search for a topic against how hard it would realistically be to rank for, what competitors are missing, and how directly it connects to an actual buying decision. A smaller but highly relevant topic often outperforms a bigger, more generic one.' },
      { q: 'What is the difference between SEO services and content marketing?', a: 'SEO covers everything that affects whether a page ranks at all: the technical setup, your site’s reputation, the content plan, and how each page is built. Content marketing is the writing and publishing side. In practice, content without SEO produces pages that are well-written but rarely found; SEO without content leaves you with a clean site and nothing worth reading. We run both as one system — the content plan is built from real search demand, and every piece is written to both rank and convert. See how <a href="/seo-services-los-angeles">technical SEO</a> and <a href="/geo-services-los-angeles">AI content writing</a> connect to the copywriting work.' },
      { q: 'What are the best practices for website content optimization?', a: 'The most reliable practices: match every page to what someone’s actually looking for, not just a keyword; put the direct answer near the top of the page; use clear headings that make the page easy to scan for both people and search engines; add FAQ sections to pages that answer specific questions; and link related pages to each other. On the technical side, the behind-the-scenes details need to be set up correctly from the first draft — adding them after the fact is less reliable. See our guide on <a href="/insights/core-web-vitals-2026">page speed and performance</a>.' },
    ],
    ctaTitle: 'Get copy that ranks and actually converts.',
  },
};
