export const SERVICES = {
  'link-building': {
    slug: 'link-building',
    pillar: 'Relations',
    title: 'Digital PR & Link Building',
    metaTitle: 'Los Angeles Link Building Services & Backlinks',
    blurb: 'Real coverage and honest links that build the kind of trust AI systems check first.',
    metaDescription: 'Los Angeles link building services and digital PR. High quality backlinks service and white hat backlinks to build domain authority and AI citations.',
    heroLines: ['Los Angeles Link Building Services', 'That Make You the Name Everyone Else Cites'],
    lede: 'Effective link building services are essential for building domain authority, but acquiring low-quality links can trigger search penalties. Whether you are looking to get backlinks for my website or scale high quality backlinks across competitive keywords, our specialized backlink building service delivers sustainable results. As a premier link builder services agency, we focus on white hat backlinks earned through genuine editorial outreach and digital PR. Our backlink builder team combines strategic link building seo with authority citations to ensure your site earns high trust from both search engines and AI assistants like ChatGPT and Perplexity. From removing spammy links with a forensic backlink service audit to executing full-funnel seo link building services, our high quality backlinks service builds lasting organic authority. Ask for a free link check to see how your backlink profile compares.',
    problem: {
      eyebrow: 'The Link Building Challenge',
      statement: 'Buying cheap links or hiring an untrusted link builder services provider can result in spam penalties. Real search growth requires a dedicated backlink building service and white hat backlinks.',
    },
    capabilities: [
      { tag: 'Outreach', title: 'Editorial Link Building Services', href: '/glossary/backlink', desc: 'The best link building services acquire editorial mentions from real industry publications through manual journalist outreach.' },
      { tag: 'Citations', title: 'High Quality Backlinks Service', href: '/glossary/nap-consistency', desc: 'Scale domain trust with a dedicated high quality backlinks service that earns authoritative context-relevant links.' },
      { tag: 'Cleanup', title: 'White Hat Backlinks & Penalty Recovery', href: '/glossary/domain-authority', desc: 'Clean up toxic spam and build white hat backlinks that follow official search engine webmaster guidelines.' },
      { tag: 'Strategy', title: 'Strategic Link Building SEO', href: '/glossary/search-entity', desc: 'Align your link building seo campaigns with target keyword hubs to maximize search rankings and page authority.' },
      { tag: 'Digital PR', title: 'Digital PR & Backlink Builder Outreach', href: '/glossary/eeat', desc: 'Our backlink builder specialists pitch data-driven stories and original surveys to journalists for high-authority press coverage.' },
      { tag: 'Audit', title: 'Technical Backlink Service & Audit', href: '/glossary/domain-authority', desc: 'Analyze every inbound link with a comprehensive backlink service audit to disavow spam and protect your site authority.' },
    ],
    process: [
      { step: '01', title: 'Backlink Service Audit', desc: 'We review your existing link profile to determine how to get backlinks for my website safely without penalty risks.' },
      { step: '02', title: 'Link Builder Services Strategy', desc: 'We build a tailored roadmap for seo link building services matching relevant media outlets and industry publications.' },
      { step: '03', title: 'White Hat Backlinks Outreach', desc: 'Our backlink building service team pitches original content to real editors to secure high quality backlinks.' },
      { step: '04', title: 'Link Building SEO Verification', desc: 'We track new mentions, verify indexing, and measure how high quality backlinks service campaigns boost search authority.' },
    ],
    faqs: [
      { q: 'What are professional link building services and how do they work?', a: 'Professional link building services help websites earn authoritative editorial links from reputable publications. Rather than buying bulk spam links, top link builder services pitch high-value content, original research, and expert quotes to real journalists. This increases search authority and improves rankings across search engines.' },
      { q: 'How can I get backlinks for my website safely?', a: 'To get backlinks for my website safely, focus on white hat backlinks earned through digital PR and original content. Using a specialized backlink building service ensures every earned link comes from a real, high-traffic domain, protecting your site from Google spam penalties.' },
      { q: 'Why are white hat backlinks better than cheap link packages?', a: 'White hat backlinks come from real publications with genuine readership, passing authentic domain authority and referral traffic. Cheap link packages rely on private blog networks (PBNs) or spam directories that trigger manual penalties. Partnering with a trusted high quality backlinks service ensures long-term organic safety.' },
      { q: 'How does link building seo affect AI search engines like ChatGPT and Perplexity?', a: 'AI search engines evaluate brand trust and entity authority when choosing which sources to cite in answers. Strategic link building seo establishes your brand as an industry leader, increasing the likelihood that AI assistants quote your site when answering user prompts.' },
      { q: 'What should I look for when selecting a backlink builder or link building agency?', a: 'When evaluating a backlink builder or agency providing seo link building services, insist on full transparency into outreach methods and acquired placements. A reliable backlink service conducts manual outreach, adheres to white-hat practices, and delivers measurable domain growth.' },
    ],
    ctaTitle: 'Build trust that holds up when people check.',
  },

  'web-dev': {
    slug: 'web-dev',
    // The free-CRM offer is a new-build promotion, so it runs on this page
    // only. ServiceTemplate renders components/SavingsOffer above the closing
    // navy banner for any service carrying this flag.
    showOffer: true,
    pillar: 'Performance',
    title: 'Web & App Development',
    metaTitle: 'Los Angeles Web Development Services | SEO-Ready',
    blurb: 'Websites built with SEO built in from day one, not added later.',
    metaDescription:
      'Los Angeles web development services with SEO and AI search visibility built in from day one. Fast custom websites that bring in local customers.',
    heroLines: ['Los Angeles Web Development', 'That Launches Already Ranking'],
    lede: 'Most web developers treat SEO as an afterthought — but a lot of sites lose search traffic before marketing even gets involved, in decisions made early about how the site is built. We build custom websites and web apps for Los Angeles businesses with search engine rankings and <a href="/services/geo">AI visibility</a> built in from the start, not added on after launch. <a href="/free-site-scan">Talk to us about your project</a> before those early decisions lock in the outcome.',
    problem: {
      eyebrow: 'The problem',
      statement: 'Agencies often hand off a beautiful site that Google can barely read, then blame SEO when the traffic never shows up — but the real damage was done months earlier, in how the site was built.',
    },
    capabilities: [
      { tag: 'Framework', title: 'Next.js & React builds', href: '/glossary/server-side-rendering', desc: 'Pages arrive as real content on the first load. No blank shell, no waiting on scripts to paint something Google already gave up on.' },
      { tag: 'Migration', title: 'Platform migrations', href: '/services/web-dev', desc: 'Leaving WordPress, Wix or an old builder is where rankings usually die. Every old address gets mapped to its new one and verified after launch, which is why yours will not.' },
      { tag: 'Systems', title: 'Component & design systems', href: '/services/web-dev', desc: 'Reusable building blocks mean your team can add pages without booking developer time for every small change.' },
      { tag: 'Performance', title: 'Infrastructure & hosting', href: '/glossary/content-delivery-network', desc: 'Hosting tuned for how fast the site feels to a real visitor, not merely whether it is technically online.' },
    ],
    process: [
      { step: '01', title: 'Technical & SEO review', desc: 'Before any code gets written: what currently ranks, what currently brings traffic, and what absolutely cannot be lost in the move.' },
      { step: '02', title: 'Structure & planning', desc: 'Then your URL structure and site architecture get planned around how people search for you. These are the decisions that are expensive to undo later.' },
      { step: '03', title: 'Build', desc: 'The build goes up piece by piece with the technical SEO already inside it, rather than as a cleanup phase nobody budgeted for.' },
      { step: '04', title: 'Launch & monitor', desc: 'Every redirect gets checked twice, and rankings stay under close watch for 30 days — the window where migration problems actually surface.' },
    ],
    faqs: [
      { q: 'Will rebuilding our site hurt our current rankings?', a: 'Only if it’s handled carelessly. The real risk isn’t the rebuild itself — it’s losing pages, redirects, or content along the way. We map every existing page to its new address and check that Google can still find everything after launch, specifically to prevent that.' },
      { q: 'Why Next.js instead of WordPress or a page builder?', a: 'Page builders trade long-term speed and control for a faster setup today. The technology we use gives us tighter control over <a href="/insights/core-web-vitals-2026">how fast your site loads</a> and a foundation that scales cleanly as your site grows — without a stack of plugins working against each other.' },
      { q: 'Do you handle ongoing development after launch, or just the initial build?', a: 'Both. Most clients move to a lighter, ongoing arrangement after launch — new pages, features, and fixes — instead of needing a whole development team, since the site is built to grow without a rebuild.' },
      { q: 'How is AI used in web development today?', a: 'AI shows up throughout the build process: it speeds up coding, helps us catch design and performance problems faster, and makes sure the technical SEO details are handled correctly from day one. We also plan for things like AI-powered search and chatbots as part of the build, not as an afterthought. We handle this as part of our development work, and can advise on which AI tools are actually worth adding — see our <a href="/services/ai-consulting">AI advice services</a> for more on that.' },
    ],
    ctaTitle: 'Build a site your marketing can actually stand on.',
  },

  'cro': {
    slug: 'cro',
    pillar: 'Performance',
    title: 'CRO & UX Analysis',
    metaTitle: 'Los Angeles Conversion Rate Optimization (CRO)',
    blurb: 'Find out exactly what’s stopping visitors from becoming customers — and fix it, backed by real data.',
    metaDescription: 'Los Angeles conversion rate optimization agency. Premier conversion rate optimization services, AI CRO, & ecommerce conversion optimization experts.',
    heroLines: ['Los Angeles Conversion Rate Optimization', 'That Turns the Traffic You Already Have Into Revenue'],
    lede: 'Getting more website traffic only builds revenue when your page turns visitors into paying customers. As a leading conversion rate optimization agency and full-service conversion rate agency, our conversion rate experts deliver tailored conversion rate optimization services that turn existing traffic into qualified sales. From mobile user testing to AI conversion rate optimization, working with a specialized conversion rate optimization company ensures every design decision is backed by real visitor behavior data. Our team includes experienced conversion rate optimization experts, dedicated conversion optimization specialist consultants, and a seasoned conversion rate optimization specialist team. Whether you need specialized conversion optimization services, global conversion rate optimisation strategies, UK conversion optimisation frameworks, or an elite ecommerce conversion rate optimization agency to scale online revenue, partnering with a top conversion optimization agency and conversion rate optimisation agency eliminates conversion drop-off. <a href="/free-site-scan">Get a free site review</a> to find out where your funnel is losing customers.',
    problem: {
      eyebrow: 'The Conversion Optimization Challenge',
      statement: 'High web traffic without sales means your user experience is leaking revenue. Partnering with a dedicated conversion rate optimization company isolates friction and unlocks revenue.',
    },
    capabilities: [
      { tag: 'Services', title: 'Conversion Rate Optimization Services', href: '/glossary/conversion-rate-optimization', desc: 'Comprehensive conversion rate optimization services analyzing visitor recordings and click maps to eliminate conversion bottlenecks.' },
      { tag: 'AI CRO', title: 'AI Conversion Rate Optimization & Testing', href: '/glossary/user-experience', desc: 'Deploy automated AI conversion rate optimization tools and multivariate A/B testing to continuously improve landing page performance.' },
      { tag: 'Ecommerce', title: 'Ecommerce Conversion Rate Optimization Agency', href: '/glossary/conversion-rate-optimization', desc: 'Our specialized ecommerce conversion rate optimization agency team streamlines checkout funnels, reduces cart abandonment, and boosts AOV.' },
      { tag: 'Audit', title: 'Conversion Optimization Specialist Audits', href: '/glossary/user-experience', desc: 'Every audit is conducted by a conversion optimization specialist or conversion rate optimization specialist to fix user friction points.' },
      { tag: 'Experts', title: 'Conversion Rate Optimization Experts & Funnels', href: '/glossary/conversion-rate-optimization', desc: 'Work directly with conversion rate experts and conversion rate optimization experts to shorten your form fills and boost qualified lead volume.' },
      { tag: 'UX Design', title: 'Conversion Rate Optimisation & UX Design', href: '/glossary/user-experience', desc: 'Combine world-class conversion rate optimisation and conversion optimisation design to deliver seamless mobile and desktop experiences.' },
    ],
    process: [
      { step: '01', title: 'Audit by Conversion Optimization Specialist', desc: 'Our conversion rate optimization specialist team reviews session recordings and heatmap data to pinpoint exact drop-off points.' },
      { step: '02', title: 'Strategic Conversion Optimization Services Plan', desc: 'We prioritize high-friction pages and design hypotheses to maximize return on ad spend and organic traffic conversion.' },
      { step: '03', title: 'Conversion Rate Optimization Agency A/B Testing', desc: 'Our conversion optimization agency executes strict split testing on headlines, CTAs, and checkout flows.' },
      { step: '04', title: 'Continuous Conversion Optimisation', desc: 'Our conversion rate agency monitors long-term performance to ensure wins hold up across seasonal shifts.' },
    ],
    faqs: [
      { q: 'What are professional conversion rate optimization services and how do they work?', a: 'Professional conversion rate optimization services systematically analyze website traffic to uncover why visitors leave without buying. A specialized conversion rate optimization company uses session replays, heatmaps, and A/B testing to turn more existing traffic into paying customers.' },
      { q: 'Why hire a conversion rate optimization agency or conversion rate agency?', a: 'Partnering with a conversion rate optimization agency or conversion rate agency gives you access to dedicated conversion rate experts who understand behavioral psychology, UX design, and data analytics. This prevents costly guesswork during site redesigns.' },
      { q: 'How does ai conversion rate optimization improve customer conversion rates?', a: 'AI conversion rate optimization leverages predictive analytics and machine learning to personalize user experiences, dynamically test copy variants, and automatically identify friction in real time.' },
      { q: 'Why should ecommerce brands partner with an ecommerce conversion rate optimization agency?', a: 'An ecommerce conversion rate optimization agency specializes in online retail metrics — optimizing product pages, cart drawers, mobile checkout speed, and cross-sell prompts to maximize revenue per visitor.' },
      { q: 'What makes conversion rate experts and conversion rate optimization experts different from standard web designers?', a: 'Standard web designers focus primarily on aesthetics. Conversion rate experts and conversion rate optimization experts design specifically for measurable conversion outcomes, testing every element against actual sales data.' },
    ],
    ctaTitle: 'Find out where your site is losing customers.',
  },

  'web-ux': {
    slug: 'web-ux',
    pillar: 'Performance',
    title: 'Web UX & Interface Design',
    metaTitle: 'Los Angeles Web UX & Interface Design',
    blurb: 'Eliminate visitor confusion and design intuitive, responsive interfaces that guide users smoothly toward conversion.',
    metaDescription: 'Los Angeles Web UX design and user experience agency. Specialized UX audits, mobile interface design, accessibility compliance, and conversion-focused UX.',
    heroLines: ['Los Angeles Web UX & Interface Design', 'That Makes the Next Step Obvious'],
    lede: 'A great user experience turns complex online interactions into effortless, intuitive journeys. As a premier Los Angeles web UX design agency and user experience consulting firm, we deliver specialized web UX services that remove interface friction, streamline mobile navigation, and improve buyer retention. From comprehensive UX audits and interactive wireframing to WCAG accessibility compliance and mobile-first interface design, working with an experienced web UX company ensures every tap, scroll, and click feels natural and intentional. Whether you are launching a modern web application, refining an enterprise portal, or redesigning an e-commerce storefront, our team of dedicated web UX specialists combines behavioral insights with modern UI aesthetics to create digital products people love to use. <a href="/free-site-scan">Get a free site scan</a> to audit your website UX and uncover usability roadblocks.',
    problem: {
      eyebrow: 'The User Experience Challenge',
      statement: 'Cluttered menus, slow micro-interactions, and confusing page layouts cause high bounce rates and lost leads. A dedicated web UX audit isolates usability friction and restores user confidence.',
    },
    capabilities: [
      { tag: 'Audit', title: 'Comprehensive Web UX Audits', href: '/glossary/user-experience', desc: 'Identify navigation hurdles, visual clutter, and layout confusion through user session recordings and task completion analysis.' },
      { tag: 'Mobile', title: 'Mobile-First UX & Touch Interface Design', href: '/glossary/core-web-vitals', desc: 'Optimize touch targets, mobile menus, and viewport responsiveness so smartphone visitors get a seamless desktop-grade experience.' },
      { tag: 'Wireframes', title: 'Interactive Wireframing & Prototyping', href: '/services/web-dev', desc: 'Map complete user journeys and test interactive prototypes before writing production code, saving valuable development time.' },
      { tag: 'Accessibility', title: 'Accessibility (a11y) & WCAG Compliance', href: '/glossary/user-experience', desc: 'Ensure your interface is fully accessible to all users, adhering to WCAG 2.1 guidelines and screen-reader standards.' },
      { tag: 'Information', title: 'Information Architecture & Site Structure', href: '/glossary/search-entity', desc: 'Organize complex content into logical, easily searchable hierarchies so users find what they need in three clicks or fewer.' },
      { tag: 'Design', title: 'Modern Interface & System UI Design', href: '/services/web-ux', desc: 'Craft cohesive design systems, micro-animations, and visual components that reinforce brand trust across every device.' },
    ],
    process: [
      { step: '01', title: 'UX Audit & Behavioral Analysis', desc: 'We review your site analytics, heatmap data, and user flows to uncover where visitors get stuck or lost.' },
      { step: '02', title: 'User Journey & Wireframe Mapping', desc: 'Our UX architects map frictionless pathways and prototype clean layout structures focused on key conversion goals.' },
      { step: '03', title: 'Interface Design & Accessibility Testing', desc: 'We build responsive UI components with clean typography, high contrast, and accessible interactive states.' },
      { step: '04', title: 'Usability Validation & Iteration', desc: 'We test real user interactions on mobile and desktop, refining micro-copy and visual hierarchy for maximum clarity.' },
    ],
    faqs: [
      { q: 'What is Web UX design and why is it vital for business growth?', a: 'Web UX (User Experience) design focuses on how visitors interact with your website. Good UX ensures pages are clear, fast, and easy to navigate, reducing bounce rates and helping visitors complete key actions like requesting a quote or making a purchase.' },
      { q: 'How does Web UX design differ from Conversion Rate Optimization (CRO)?', a: 'Web UX focuses on overall user satisfaction, interface clarity, accessibility, and navigation ease. CRO specifically tests and optimizes pages to maximize conversion metrics (sales or lead signups). Excellent Web UX lays the groundwork for high CRO performance.' },
      { q: 'Why is mobile-first UX design so critical today?', a: 'Over 65% of search traffic originates on mobile devices. A mobile-first UX approach ensures buttons, forms, menus, and typography are optimized for small touchscreens first, preventing user frustration.' },
      { q: 'What happens during a professional Web UX audit?', a: 'A professional Web UX audit evaluates your website against usability standards, accessibility rules, visual hierarchy principles, and real visitor recording data to highlight exact areas causing drop-offs.' },
    ],
    ctaTitle: 'Build a web experience visitors enjoy using.',
  },

  'ai-consulting': {
    slug: 'ai-consulting',
    pillar: 'Performance',
    title: 'AI & LLM Systems Consulting',
    metaTitle: 'Los Angeles AI Consulting Services for Business',
    blurb: 'Straight answers on which AI tools are actually worth using for your business — then we build them.',
    metaDescription:
      'Los Angeles AI consulting services. We help local LA businesses test and build practical AI tools for search visibility, automation, and lead growth.',
    heroLines: ['Los Angeles AI Consulting', 'That Puts the Busywork on Autopilot'],
    lede: 'Right now, software vendors are pitching endless AI features, but most don’t deliver once you try them. We help Los Angeles businesses figure out what’s genuinely useful — like AI-assisted content, <a href="/services/geo">getting found by AI search tools</a>, and automating repetitive tasks — then build the parts worth building. <a href="/free-site-scan">Ask for a free AI review</a> to find out what’s worth spending on.',
    problem: {
      eyebrow: 'The problem',
      statement: 'Business owners feel pressure to “do something with AI,” and a lot of what gets bought in response either duplicates a tool they already have, or solves a problem that was never actually real.',
    },
    capabilities: [
      { tag: 'Strategy', title: 'AI readiness review', href: '/services/ai-consulting', desc: 'An honest read on where AI genuinely helps your business — including the parts where the honest answer is that it does not.' },
      { tag: 'Search', title: 'AI search & visibility setup', href: '/glossary/generative-engine-optimization', desc: 'Google AI answers, ChatGPT and Perplexity each choose their sources differently. We set your site up for how they actually decide, not how people assume they do.' },
      { tag: 'Automation', title: 'Workflow automation', href: '/services/ai-consulting', desc: 'The real wins here are boring and valuable: reporting, research, and the content chores quietly eating a day a week.' },
      { tag: 'Chat', title: 'Chatbot & assistant setup', href: '/glossary/large-language-model', desc: 'A chat assistant trained on your real content, with clear limits on what it will attempt. Most bad AI chat comes from asking it to do too much.' },
    ],
    process: [
      { step: '01', title: 'Readiness review', desc: 'First a look at the tools, workflows and content you already run, and where AI would realistically change the outcome.' },
      { step: '02', title: 'Prioritize & scope', desc: 'Ideas get ranked by effort against impact, and most get cut. That is the point of the exercise.' },
      { step: '03', title: 'Build it', desc: 'Whatever survives gets built and tested against real examples before anyone in your business has to depend on it.' },
      { step: '04', title: 'Train & monitor', desc: 'Your team gets trained on it, and it stays watched through the early weeks, while bad habits are still easy to correct.' },
    ],
    faqs: [
      { q: 'Do we need our own AI strategy, or can we just adopt what our tools already offer?', a: 'Most off-the-shelf AI features are generic by design. A real strategy matters when the use is specific to your business — your content, the questions your customers actually ask, the bottlenecks slowing your team down — which is usually where the real value is.' },
      { q: 'Is this the same as your GEO and AI content work?', a: 'They’re related, but not the same. <a href="/services/geo">Our content writing service</a> is about getting your existing pages recommended by AI tools. This is broader — reviewing and setting up AI tools across your whole business, whether that involves content or not.' },
      { q: 'We’re worried about AI tools producing generic or inaccurate output. How do you handle that?', a: 'Any AI tool we build is kept narrowly focused and trained on your actual content and information, with a clear line around what it should and shouldn’t try to do. Generic, made-up answers are usually a sign of a tool being asked to do too much — not something AI can never get right.' },
      { q: 'What is the best AI SEO software in 2026?', a: 'It depends on the problem you’re solving. For technical checks and rank tracking, tools like Semrush, Ahrefs, and Screaming Frog are still the standard. For tracking whether your brand shows up in ChatGPT, Perplexity, or Google’s AI answers, tools like SE Ranking and Profound are built for that, alongside manually testing prompts yourself. For AI-assisted content research, the quality gap between tools is significant. We cover this in more detail in our <a href="/insights/ai-seo-tools-compared">AI SEO tools comparison</a> and help clients choose the right tools as part of our consulting work.' },
      { q: 'How do AI tools improve digital marketing workflows?', a: 'The biggest wins from AI in marketing show up in research: it cuts down the time needed to find keyword groups, spot gaps in your content, study competitor pages, and understand what people are actually searching for. Automating reports is another consistent win. Where AI falls short is when it’s left to write content without a person checking it — that tends to produce generic writing that underperforms real, human-written work. The right approach is AI for research, humans for the final writing and decisions. See our <a href="/services/geo">content writing work</a> for how we apply this in practice.' },
    ],
    ctaTitle: 'Figure out what AI is actually worth building.',
  },
};
