// Flat, keyword-first service pages — "back to basics" title/H1/intro format,
// each backed by a real testimonial and a real, already-verified datapoint
// (never fabricated — same bar as lib/searchWins.js and lib/clientSearchWins.js).
// These 4 pages replace 4 of the 7 entries that used to live in lib/services.js
// under /services/[slug]; see next.config.mjs for the 301 redirects from the
// old URLs. The other 3 services (authority-link-building, cro-ux,
// ai-llm-consulting) plus web-app-development stay at their existing URLs,
// untouched by this restructuring.

export const SERVICES_FLAT = {
  'seo-services': {
    slug: 'seo-services',
    title: 'SEO Services - Get Found on Google and AI Tools',
    eyebrow: 'SEO Services · Get Found on Google',
    h1: 'First, make sure they can actually see you.',
    heroCtaText: 'Request a Free SEO Check',
    heroCtaHref: '/onboarding?goal=rankings',
    metaDescription: 'SEO services that fix the technical problems keeping Google and AI tools from reading your site properly. See real client results and get a free audit.',
    intro: 'SEO should start with one simple question: can Google actually read your page? If it can’t, no amount of content or links will save you. We fix that basic technical problem first — making sure your site loads properly and search engines can find and understand it — before building content and trust on top of that foundation. It’s the same approach that took SafetyCentric’s organic search impressions up 113% in 90 days, verified directly in Google Search Console. Request a free SEO check to see what’s actually capping your traffic.',
    testimonial: {
      quote: 'Moving off WordPress was the part I was most nervous about and it turned out to be the easy part. The bigger deal was the CRM and the drip campaigns — leads used to sit in an inbox until someone remembered them. Now they get followed up whether I’m paying attention or not.',
      name: 'Pete Urueta',
      company: 'Safety-Centric.com',
      role: 'Business Security Systems Services',
      photo: '/assets/img/pete-urueta-ceo.webp',
      href: '/work/safetycentric',
    },
    datapoint: {
      value: 113,
      decimals: 0,
      suffix: '%',
      label: 'Increase in organic search impressions for one client in 90 days',
      sourceNote: 'Verified in Google Search Console — see the live number on the SafetyCentric case study.',
      href: '/work/safetycentric',
    },
    problem: {
      eyebrow: 'The problem',
      statement: 'A site can look finished and still be invisible to Google — blocked pages, a blank screen where content should load, and missing technical details quietly capping your traffic no matter how much content you publish on top of it.',
    },
    capabilities: [
      { tag: 'Rendering', title: 'Server-side rendering', desc: 'We fix websites that show Google a blank page even though they look fine in a browser, so search engines can actually see your real content.' },
      { tag: 'Recovery', title: 'Algorithm & penalty recovery', desc: 'We figure out whether a traffic drop is from a Google update or a direct penalty, and build the right recovery plan for whichever one it is.' },
      { tag: 'Schema', title: 'Structured data', desc: 'We add clear, behind-the-scenes details about your business, services, and FAQs — the same information AI tools use to confirm what your business actually is.' },
      { tag: 'Speed', title: 'Core Web Vitals', desc: 'We tune your site’s loading speed and stability to pass Google’s standards, without a pile of conflicting plugins fighting each other.' },
    ],
    process: [
      { step: '01', title: 'Technical audit', desc: 'A full test of what Google and AI tools actually see when they visit your site — not just what you see in your browser.' },
      { step: '02', title: 'Fix the foundation', desc: 'We fix the basic technical problems keeping Google from finding and reading your pages, before touching anything else.' },
      { step: '03', title: 'Structured data & layout', desc: 'We add the right behind-the-scenes details and organize your site to match how people in your industry actually search.' },
      { step: '04', title: 'Verify & monitor', desc: 'We confirm the fixes in Google Search Console, keep monitoring your site, and keep a clear record of what changed and when.' },
    ],
    faqs: [
      { q: 'How do we know if our traffic drop is an algorithm update or something we did?', a: 'We compare the date of your drop against known Google updates, look at which pages and search terms lost traffic, and check Search Console for any direct penalty notices. A Google update usually hits a broad group of pages at once; a direct penalty comes with a clear notice and follows a specific rule violation.' },
      { q: 'Our developer says the site is fast. Why isn’t it ranking?', a: 'Loading fast in a browser and being readable to Google are two different things. A site can score well on a speed test and still show search engines a blank page if all the content loads after the page opens. We test your site the same way search engines and AI tools actually see it, not just with a speed score.' },
      { q: 'Do we need to rebuild our whole site to fix this?', a: 'Usually not. Most technical SEO problems can be fixed without starting over — the underlying issues can typically be layered onto your existing website. A <a href="/services/web-app-development">full rebuild</a> is only the right call when your current platform genuinely can’t be fixed.' },
      { q: 'What is an organic search strategy?', a: 'An organic search strategy is your plan for earning free search traffic instead of paying for every click — it covers the technical setup, the right keywords, how your content is organized, and building real trust so your pages match what people are actually searching for. Unlike paid ads, good rankings keep paying off over time, long after the initial work is done. We start with the technical basics, then build content and trust on top. See real examples in our <a href="/work">client case studies</a>.' },
      { q: 'How have search engine algorithms evolved?', a: 'Search engines have moved from simply matching keywords to actually understanding what a page means and how trustworthy it is. Early updates like Panda and Penguin punished thin content and fake links. Later updates helped Google understand the meaning behind a search, not just the exact words typed in. More recent updates reward real expertise and genuinely useful content. AI Overviews add a new layer on top: content now competes to be quoted by AI, not just ranked in a list. We’ve tracked and adjusted to every major update since 2010. See our guide on <a href="/insights/why-did-my-website-traffic-drop">figuring out why your traffic dropped</a>.' },
    ],
    ctaTitle: 'Find out what’s actually capping your traffic.',
  },

  'geo-services': {
    slug: 'geo-services',
    title: 'GEO Services - Get Found by ChatGPT and Google AI',
    eyebrow: 'GEO Services · Get Found by AI Tools Like ChatGPT',
    h1: 'Written so AI wants to quote it.',
    metaDescription: 'GEO services built to get your content mentioned by ChatGPT, Perplexity, and Google’s AI answers — not just ranked. See our AI citation research and get a free audit.',
    intro: 'AI tools like ChatGPT don’t reward typical marketing copy — they pull clear, direct answers from pages they already trust. We write your content around the exact questions your customers are actually asking ChatGPT and Perplexity, so your page is the one that gets quoted, not just listed somewhere on page two. We back this up with real research: our AI Citation Study asked five different AI assistants the same 200 questions and tracked exactly who they recommended, and why. One client, The Healing Metta, now shows up when people ask ChatGPT about integrative care in their area — that wasn’t true a year ago. Request a free content check to see where you’re missing out on AI recommendations.',
    testimonial: {
      quote: 'Users were finding answers about our treatments everywhere except from us. The shift was writing for the questions people actually ask, and structuring it so the AI tools could read it properly. When someone asks ChatGPT about integrative care in our area now, we come up. That wasn’t true a year ago.',
      name: null,
      company: 'The Healing Metta',
      role: 'Secrets of Buddha',
      photo: null,
      href: '/work/the-healing-metta',
    },
    datapoint: {
      value: 34,
      decimals: 0,
      suffix: '%',
      label: 'Growth in blended organic search visibility across every account we run this quarter',
      sourceNote: 'The same underlying visibility AI answer engines pull from — see our AI Citation Study for how we track actual AI citations directly.',
      href: '/insights/ai-citation-study',
    },
    problem: {
      eyebrow: 'The problem',
      statement: 'Most website writing is meant to persuade a person scrolling down a page — not to be read and quoted by an AI tool looking for a clear, direct answer to a specific question.',
    },
    capabilities: [
      { tag: 'Structure', title: 'Answer-first writing', desc: 'Clear, direct answers placed right where AI tools look for them, backed up with the detail that earns real trust.' },
      { tag: 'Research', title: 'Prompt-mapped content', desc: 'Content built around the real questions people actually type into ChatGPT and Perplexity, not just Google keyword numbers.' },
      { tag: 'Format', title: 'FAQ & comparison pages', desc: 'The page styles AI tools quote most often — clear questions, direct answers, and easy-to-scan comparisons.' },
      { tag: 'Voice', title: 'SEO-mapped web copy', desc: 'Your main site and service pages written to actually rank and bring in customers, not just fill space around a keyword.' },
    ],
    process: [
      { step: '01', title: 'Question research', desc: 'We find out what people actually ask AI tools and Google about businesses like yours.' },
      { step: '02', title: 'Content planning', desc: 'We build a page structure that answers the main question fast, then earns attention with real depth underneath.' },
      { step: '03', title: 'Write & structure', desc: 'We write and organize the page so it’s clear for both real readers and AI tools.' },
      { step: '04', title: 'Track citations', desc: 'We check whether your content is actually getting mentioned in AI answers, not just sitting indexed somewhere.' },
    ],
    faqs: [
      { q: 'Is this just SEO copywriting with a new name?', a: 'It shares the same foundation as our <a href="/content-marketing-services">content marketing</a> work — clear, well-organized, genuinely useful writing. This adds one more layer, specific to how AI tools pull information: a direct answer near the top, clear structure, and wording that’s easy to quote without losing its meaning.' },
      { q: 'Can you rewrite our existing content instead of starting from scratch?', a: 'In most cases, yes. A lot of underperforming pages already have the right information — they just need to be reorganized around a direct answer and cleaner formatting. We check your existing pages first and only recommend starting over when the content itself is too thin to fix.' },
      { q: 'How do you measure whether this is working?', a: 'We track two things: your regular Google rankings and traffic, and whether AI tools are actually mentioning you — <a href="/insights/get-cited-by-chatgpt-perplexity-ai-overviews">running your target questions through ChatGPT, Perplexity, and Google’s AI answers</a> regularly to see if your pages get quoted.' },
      { q: 'What AI marketing tools does Gobiya use for content optimization?', a: 'We use AI tools for research — finding the actual questions people ask ChatGPT and Perplexity — plus organizing content and tracking whether client pages get mentioned. The actual writing and editorial decisions stay with our team: AI tools speed up research, they don’t replace human judgment. For a broader look at choosing and using AI tools across your business, see our <a href="/services/ai-llm-consulting">AI consulting</a> work.' },
      { q: 'How does AI change search engine results pages?', a: 'AI has added a new layer at the top of the page — Google’s AI Overviews, and the answer screens in ChatGPT and Perplexity — that summarizes and quotes sources before someone even clicks a link. Your content now competes two ways: the usual ranking for a spot in the list, and separately, getting picked to be part of that AI summary. Those two things follow different rules, which is why <a href="/ai-visibility">getting found by AI tools</a> is now its own skill alongside traditional SEO. Read more in our guide on <a href="/insights/zero-click-search-ai-overviews-small-business">what it means when people stop clicking links at all</a>.' },
    ],
    ctaTitle: 'Write content an AI actually wants to quote.',
  },

  'ppc-management-services': {
    slug: 'ppc-management-services',
    title: 'PPC Management Services - Google Ads That Bring Real Customers',
    eyebrow: 'PPC Management Services · Cost Per Lead, Not Clicks',
    h1: 'Stop paying for clicks that were never going to buy.',
    heroCtaText: 'Request a Free Ads Check',
    heroCtaHref: '/onboarding?goal=sales',
    metaDescription: 'Google Ads management built around getting real customers, not just clicks — better campaigns, matching landing pages, and tracking that shows what’s actually working. Free ad account check.',
    intro: 'Most Google Ads management focuses on getting clicks, not booked customers. We rebuild your campaigns, block out the searches that waste your budget, and match your landing pages around the one number that actually matters — the cost of a real, paying customer. Every account gets a full review before we change a dollar of spend. One client, Trusted Home Contractors, cut their cost per real customer by roughly 40% once we rebuilt campaigns around what people were actually searching for and sent them to pages that matched. Request a free Google Ads check to see where your budget is leaking.',
    testimonial: {
      quote: 'Our ads were working in the sense that the phone rang. They weren’t working in the sense that most of those calls were tire-kickers. Rebuilding the campaigns around what people were actually searching for, and sending them to pages that matched, cut what we pay per real customer by about 40%.',
      name: 'Mike P.',
      company: 'Trusted Home Contractors',
      role: 'General Contractor',
      photo: '/assets/img/testimonial-mike.png',
      href: '/work',
    },
    datapoint: {
      value: 40,
      decimals: 0,
      suffix: '%',
      label: 'Reduction in cost per real customer for one client',
      sourceNote: 'Client-reported result — PPC spend isn’t tracked in Google Search Console, so this is the account’s own reporting, not GSC-verified.',
      href: '/work',
    },
    problem: {
      eyebrow: 'The problem',
      statement: 'Loosely-matched keywords, a short block-list, and a landing page that doesn’t match what people searched for quietly burn your budget on clicks that were never going to become customers.',
    },
    capabilities: [
      { tag: 'Structure', title: 'Campaign rebuilds', desc: 'Tightly organized ad groups and a block-list we update every week, to stop wasted spend at the source.' },
      { tag: 'Conversion', title: 'Landing page alignment', desc: 'Landing pages built or rebuilt to match exactly what someone searched for, so the ad and the page make the same promise.' },
      { tag: 'Tracking', title: 'Conversion & call tracking', desc: 'Tracking wired all the way to real bookings and phone calls, not just form fills, so your budget follows actual revenue.' },
      { tag: 'Testing', title: 'Bid & creative testing', desc: 'Ongoing testing of bids and ad copy measured against the cost of a real lead, not just how many people click.' },
      { tag: 'Production', title: 'AI-generated video assets', desc: 'Campaign videos made with AI tools, turned around in days instead of a full camera shoot.' },
      { tag: 'Variants', title: 'Creative variant testing', desc: 'Several different video hooks and edits produced quickly, so we can test what actually performs instead of guessing.' },
    ],
    process: [
      { step: '01', title: 'Account review', desc: 'A full review of your current spend and keywords, to find exactly where budget is leaking on the wrong clicks.' },
      { step: '02', title: 'Rebuild structure', desc: 'We reorganize your campaigns around real buyer intent and immediately block out the searches that waste money.' },
      { step: '03', title: 'Align landing pages', desc: 'We build or adjust landing pages to match exactly what each ad promises, closing the gap between the click and the sale.' },
      { step: '04', title: 'Optimize to cost per lead', desc: 'Ongoing decisions about bids, budget, and ad creative, all measured against the cost of a real booked lead, reported to you every month.' },
    ],
    faqs: [
      { q: 'Our click-through rate is good — why is cost per lead still high?', a: 'How many people click your ad only shows whether the ad is eye-catching — it doesn’t show whether that traffic actually turns into customers. A lot of clicks but a high cost per lead usually means loosely-matched keywords are pulling in the wrong people, or your landing page doesn’t follow through on what the ad promised.' },
      { q: 'How much should we be spending on Google Ads?', a: 'It depends on how much profit you make per customer and what a lead currently costs you — not a general rule of thumb. We usually start by rebuilding your campaigns within your existing budget to prove real improvement before recommending you spend more.' },
      { q: 'Do you handle both the ads and the landing pages?', a: 'Yes — matching the ad and the landing page is usually where the biggest gains come from, and it overlaps directly with our <a href="/services/cro-ux">website testing</a> work. A well-run campaign sending traffic to a generic homepage still underperforms. Matching the landing page to what each ad actually promised is often the single biggest fix we make.' },
      { q: 'Does AI-generated video actually perform as well as traditionally produced ads?', a: 'It depends on the format and platform. For short, attention-grabbing social ads, AI-made video performs just as well because viewers care about the message and pacing more than polish. For your main brand video, a traditional shoot may still be the better call.' },
    ],
    ctaTitle: 'Rebuild your ad account around cost per lead, not clicks.',
  },

  'content-marketing-services': {
    slug: 'content-marketing-services',
    title: 'Content Marketing Services - Writing That Gets Found and Read',
    eyebrow: 'Content Marketing Services · Written to Rank and Convert',
    h1: 'Words built to be found — and still sound like you.',
    metaDescription: 'Content marketing services that turn articles into real search growth, planned around what people are actually searching for. Free content check.',
    intro: 'Content marketing usually fails for one simple reason: pages get written to fill a calendar instead of answering a question people are actually searching for. We plan our content around real demand first, then write it to both rank and bring in customers — not just to hit a word count. One client, RemodelMePros, put it simply: the SEO articles kept homeowners coming in without buying every lead. That same approach took SmileCenter’s organic search impressions up 56% in 90 days, verified in Google Search Console. Request a free content check to see where your current pages are missing real demand.',
    testimonial: {
      quote: 'Two-sided marketplaces are hard and I’d already had one developer tell me it couldn’t be done for what I wanted to spend. The bidding dashboard is what contractors actually log in for, and the SEO articles kept homeowners coming in without me buying every lead. It’s not finished — it probably never is — but it works.',
      name: 'Mike P.',
      company: 'RemodelMePros.com',
      role: 'Contractors Marketplace',
      photo: '/assets/img/testimonial-mike.png',
      href: '/work/remodel-me-pros',
    },
    datapoint: {
      value: 56,
      decimals: 0,
      suffix: '%',
      label: 'Increase in organic search impressions from a content-driven rebuild',
      sourceNote: 'A different client (SmileCenter.com) than the testimonial above, verified in Google Search Console — see the live number on their case study.',
      href: '/work/smile-center-dentistry',
    },
    problem: {
      eyebrow: 'The problem',
      statement: 'Copy stuffed with keywords might rank briefly, but it doesn’t convince anyone to buy. Well-written copy that ignores what people are searching for never gets found in the first place. Most sites end up with one problem or the other.',
    },
    capabilities: [
      { tag: 'Pages', title: 'Core site copy', desc: 'Homepage, service, and about pages written around what people are actually searching for, with a clear path to becoming a customer — not just packed with keywords.' },
      { tag: 'Intent', title: 'Search intent mapping', desc: 'Every page built around what someone actually wants when they search that term, not just the exact words they typed.' },
      { tag: 'Voice', title: 'Brand voice development', desc: 'A consistent voice defined once and used across every page, so the site reads like one real business, not a mix of different writers.' },
      { tag: 'Structure', title: 'On-page structure & schema', desc: 'Headings and behind-the-scenes technical details built into every page from the first draft, not added on afterward.' },
      { tag: 'Research', title: 'Topic & gap analysis', desc: 'We study real search demand and what competitors are covering to find topics genuinely worth writing about, not just easy ones.' },
      { tag: 'Architecture', title: 'Content hub planning', desc: 'Groups of related articles built to reinforce each other, instead of competing against your own pages for the same ranking.' },
    ],
    process: [
      { step: '01', title: 'Intent & keyword research', desc: 'We map out what people actually search for and expect to find, page by page, before any writing starts.' },
      { step: '02', title: 'Structure & outline', desc: 'We plan the page layout and headings around both what people are searching for and a clear path to becoming a customer.' },
      { step: '03', title: 'Write & optimize', desc: 'We write and edit the copy, with the technical SEO details built in from the start.' },
      { step: '04', title: 'Review & publish', desc: 'You review it, we publish it, and we keep an eye on whether Google picks it up afterward.' },
    ],
    faqs: [
      { q: 'Will this copy sound like it was written for search engines instead of people?', a: 'That’s exactly what we try to avoid. Good SEO writing today works by genuinely answering what someone’s looking for, in a clear, natural voice — stuffing keywords into a page has actually hurt rankings for years now.' },
      { q: 'Can you write copy for our existing pages, or only new ones?', a: 'Both. A lot of our work is rewriting existing pages that rank poorly or don’t convert, often because they were written for a different question than the one that actually brings in traffic.' },
      { q: 'How do you make sure the copy still sounds like our brand?', a: 'We start by reviewing your existing materials and how your team actually talks to customers, before writing anything. That way the copy sounds like an extension of your business, not a generic template.' },
      { q: 'How much content do we actually need to publish?', a: 'Less than most agencies suggest. A smaller number of well-researched, well-organized pieces aimed at real demand consistently beats a big calendar of thin, low-value posts.' },
      { q: 'How do you decide what topics are worth covering?', a: 'We weigh how many people search for a topic against how hard it would realistically be to rank for, what competitors are missing, and how directly it connects to an actual buying decision. A smaller but highly relevant topic often outperforms a bigger, more generic one.' },
      { q: 'What is the difference between SEO services and content marketing?', a: 'SEO covers everything that affects whether a page ranks at all: the technical setup, your site’s reputation, the content plan, and how each page is built. Content marketing is the writing and publishing side. In practice, content without SEO produces pages that are well-written but rarely found; SEO without content leaves you with a clean site and nothing worth reading. We run both as one system — the content plan is built from real search demand, and every piece is written to both rank and convert. See how <a href="/seo-services">technical SEO</a> and <a href="/geo-services">AI content writing</a> connect to the copywriting work.' },
      { q: 'What are the best practices for website content optimization?', a: 'The most reliable practices: match every page to what someone’s actually looking for, not just a keyword; put the direct answer near the top of the page; use clear headings that make the page easy to scan for both people and search engines; add FAQ sections to pages that answer specific questions; and link related pages to each other. On the technical side, the behind-the-scenes details need to be set up correctly from the first draft — adding them after the fact is less reliable. See our guide on <a href="/insights/core-web-vitals-2026">page speed and performance</a>.' },
    ],
    ctaTitle: 'Get copy that ranks and actually converts.',
  },
};
