export const CASE_STUDIES = [
  {
    client: 'Smile Center Dentistry',
    tag: 'Healthcare & Dental',
    result: '5x increase in patient inquiries',
    desc: 'A full technical SEO rebuild and local search overhaul turned a barely-findable practice site into the top local result for its core procedures — with patient inquiries following directly.',
    industryHref: '/industries/healthcare',
    outcomeHref: '/outcomes/traffic',
  },
  {
    client: 'American Livescan',
    tag: 'Local Service Business',
    result: '3x increase in online bookings',
    desc: 'Google Business Profile optimization and a rebuilt booking path turned local fingerprinting searches into scheduled appointments, without adding ad spend.',
    industryHref: '/industries/local-service',
    outcomeHref: '/outcomes/sales',
  },
  {
    client: 'SafetyCentric',
    tag: 'Professional Services',
    result: 'Authority rebuilt after a name change',
    desc: 'Editorial link acquisition and citation cleanup re-established domain trust for a security integration firm after a brand transition threatened to reset its search equity.',
    industryHref: '/industries/professional-services',
    outcomeHref: '/outcomes/rankings',
  },
  {
    client: 'QuickPass AiD',
    tag: 'Local Service Business',
    result: 'Technical foundation rebuilt for indexation',
    desc: 'A client-side-only site that was invisible to crawlers was rebuilt server-rendered, unlocking indexation for an identity-verification service across multiple locations.',
    industryHref: '/industries/local-service',
    outcomeHref: '/outcomes/traffic',
  },
  {
    client: 'Remodel Me Pros',
    tag: 'Local Service Business',
    result: '61% reduction in cost per lead',
    desc: 'A Google Ads rebuild — tighter match types, aggressive negative keywords, landing pages matched to intent — cut wasted spend without cutting lead volume.',
    industryHref: '/industries/local-service',
    outcomeHref: '/outcomes/sales',
  },
  {
    client: 'Medicine Metta',
    tag: 'Healthcare & Dental',
    result: 'Structured for AI-answer citation',
    desc: 'Patient-question content and clean schema markup positioned an integrative wellness practice to be cited directly in AI Overviews and ChatGPT answers, not just ranked.',
    industryHref: '/industries/healthcare',
    outcomeHref: '/outcomes/rankings',
  },
  {
    client: 'Total Capital',
    tag: 'Enterprise & B2B',
    result: '5.7x return on Google Ads spend',
    desc: 'A campaign rebuild around qualified-lead intent, on a $15K/month budget, turned an underperforming account into one of the strongest ROAS accounts in the portfolio.',
    industryHref: '/industries/enterprise-b2b',
    outcomeHref: '/outcomes/sales',
  },
  {
    client: 'Tidder',
    tag: 'Enterprise & B2B',
    result: 'Custom Next.js platform, built to scale',
    desc: 'A legacy platform migration to a custom Next.js build gave a growing B2B product the rendering performance and structured-data foundation to scale search visibility with the product.',
    industryHref: '/industries/enterprise-b2b',
    outcomeHref: '/outcomes/traffic',
  },
];
